### ISSUE TITLE
It doesn't work with vimplug (sadly)

### ISSUE THREAD

**Issue by MarcusXavierr** [MeanderingProgrammer/markdown.nvim#39]
I've installed the plugin with vimplug and made the setup

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/14d69e25-f556-4023-a16b-4c72b48b108b)

The setup seems to be successful, because the command is avaliable on neovim

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/d0e7d31d-e9fd-417a-ab28-025a882e8a73)

But when I run this, nothing happens

P.s.: 

I have markdown parser installed on treesitter
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/e7c13cc4-0bc9-4548-9239-4a2acd5c9565)

**Comment by MeanderingProgrammer** [comment]
Huh, that is interesting. I don't have any familiarity with vim plug, but hopefully we can get it working. 

Can you run the checkhealth command 'checkhealth render-markdown', see if that has any information. 

Also which version of Neovim are you running and on what OS?

**Comment by MarcusXavierr** [comment]
@MeanderingProgrammer This erros occurs
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/105b459e-46c5-4682-b4b3-48b3e2351b73)

**Comment by MeanderingProgrammer** [comment]
Ah, damn, I thought I still had compatibility with `0.9.5`, but looks like `list_contains` was added in `0.10.0`.

I pushed a small change that should resolve the health check failing. Can you update the plugin and run it again, just as a sanity check.

Maybe the reason this isn't working is I'm using some other API that's not compatible with `0.9.5`. I haven't found a good way to determine which APIs existed for which versions of Neovim. However in that case the error should be printed out and pretty obvious, which doesn't seem to be happening right?

**Comment by MarcusXavierr** [comment]
I've updated, and the checkhealt seems ok, but it's still not working

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/08f1650c-ce18-4606-b05d-2c475cbb168b)

I've also downloaded the neovim 0.10.0 binary and used it, but still not worked

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/7e8401a0-cba3-4f6d-bfb1-7c5fc1f046f4)

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/765582b5-43e0-4ac1-a8dd-d14b48031367)

**Comment by MeanderingProgrammer** [comment]
Oh, sorry about that, didn't mean for you to need to update the version of neovim you use, but appreciate the thoroughness!

Lets see if the logs can help.

Can you enable debug logs by updating the plugin config to:

```lua
require('render-markdown').setup({ log_level = 'debug' })
```

Then create a new markdown file with the following content, just so I can compare my output to yours:

```text
# Heading

- Item
  - Nested

> [!NOTE]
> A note

- [ ] Unchecked
- [x] Checked
```

Open the file, the plugin will try to render it, then close the file.

Then copy the output of the log file which will most likely be located at `~/.local/state/nvim/render-markdown.log`, and paste the results here.

**Comment by MarcusXavierr** [comment]
I've set the log_level to debug, then opened the file with this content. But it didn't seem to create a log file
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/596ea20b-4fa6-4c5d-8816-d5b75b763636)

**Comment by MarcusXavierr** [comment]
I put a print on the toggle function, and it seems to be called

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/bb8546c9-6d55-441a-8fc6-0a242da91ca7)


![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/7f1ba53e-c754-4485-b2ee-f37182699a92)

**Comment by MarcusXavierr** [comment]
It early returns at this `clear_valid` function

**Comment by MarcusXavierr** [comment]
Mistery solved! As I use vimwiki, my markdown files are for some reason being recognized as vimwiki files. 

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/f5c94441-b032-45be-bf96-189c66876b80)

If I add the vimwiki option at filetypes, it crashes :(
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/6f7bfebc-0c6f-4789-819f-db04f239ff05)

![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/c06fd0c6-4d9a-4b69-80a9-c027eab47990)

if I remove vimwiki 
![image](https://github.com/MeanderingProgrammer/markdown.nvim/assets/59923581/645a9d2d-5a59-4b15-877b-8e6c3ef62e2d)

**Comment by MarcusXavierr** [comment]
Set the filetype to markdown with autocmd seems the best workaround. I continue with vimwiki working and the markdown plugin works too. The only issue is that the autocmd does not works every time

**Comment by MeanderingProgrammer** [comment]
Ah that makes sense, parsers are picked using the `vim.treesitter` apis and `vimwiki` both sets the filetype and doesn't have an associated parser, so we run into this error.

Instead of the `autocommands` another options would be to do the following two things (at least I think this would work lmk if it does!):

1. Add `vimwiki` to the `file_types` this plugin runs on:

```lua
require('render-markdown').setup({
  file_types = { 'markdown', 'vimwiki' },
})
```

2. Register `markdown` as the parser for `vimwiki` files:

```lua
vim.treesitter.language.register('markdown', 'vimwiki')
```

**Comment by MarcusXavierr** [comment]
It worked pretty well. Thanks

Maybe it's good to put a Notice to vimwiki users on readme

**Comment by MeanderingProgrammer** [comment]
Done: https://github.com/MeanderingProgrammer/markdown.nvim?tab=readme-ov-file#for-vimwiki-users

Thanks reaching out!
